feat: Add google login
plan-with-me/pwm-fe pull request #2
Opened 2024-04-30 15:51 UTC by 5pponent

2024-04-30 15:55 UTC, 5pponent reviewed
서버가 현재 업데이트가 안돼서 추후 테스트해보겠습니다

2024-04-30 15:55 UTC, 5pponent commented on package.json
> +    "@react-oauth/google": "^0.12.1",
구글 로그인용 라이브러리 react-oauth/google 추가했습니다

2024-04-30 15:55 UTC, 5pponent commented on src/api/config.tsx
> +const api = axios.create({
나중에 서버 로그인하고 요청시마다 authorization 헤더에 토큰 포함해서 보낼 수 있도록 axios 유틸 구현했습니다

2024-04-30 15:55 UTC, 5pponent commented on src/pages/Login.tsx
> +          <GoogleOAuthProvider
구글 로그인 라이브러리 사용하여 로그인 버튼 구현했습니다

2024-04-30 15:55 UTC, 5pponent commented on src/pages/Login.tsx
> +  const handleGoogleCredential = async (credentialResponse: credentialResponse) => {
구글 로그인 성공 시 받아온 id 토큰을 서버로 넘기는 함수입니다

2024-05-01 00:55 UTC, hyeonhe requested changes

2024-05-01 00:55 UTC, hyeonhe commented on src/pages/Login.tsx
> +              useOneTap
이거는 굳이 없어도 될것 같아요

2024-05-01 02:18 UTC, 5pponent commented on src/pages/Login.tsx
> +              useOneTap
수정햇습니다

2024-05-01 02:49 UTC, hyeonhe approved these changes

2024-05-01 02:50 UTC, merged